xcodeproj 'RGKit Tests'
workspace '../RGKit'
# inhibit_all_warnings!

platform :ios, '5.0'

target 'iOS Tests' do
    pod 'RGKit', :path => '../'
  # podspec :path => '../AFNetworking.podspec'

  # pod 'OCMock', '~> 2.1.1'
  # pod 'Expecta', '~> 0.2.1'
  # pod 'AFHTTPRequestOperationLogger', '~> 0.10.0'
  # pod 'LRMocky', :git => 'https://github.com/rhgills/LRMocky/', :branch => 'v0.9.x'
  # # :git => 'https://github.com/rhgills/LRMocky/', :branch => 'v0.9.x'
  # # :path => '/Users/rhgill/Code/LRMocky'
  # pod 'OCHamcrest'
  # pod 'OHHTTPStubs'
end


